select * from dbo.customer_shopping_behavior
select count(*) from dbo.customer_shopping_behavior


SELECT COUNT(c.review_rating) AS [null values]
FROM dbo.customer_shopping_behavior AS c
WHERE c.review_rating IS NULL;





--Q1. What is the total revenue generated by male vs. female customers?

SELECT 
    c.gender,                     -- Shows each gender group
    SUM(c.purchase_amount) AS revenue  -- Calculates total purchase amount for each gender
FROM 
    dbo.customer_shopping_behavior AS c  -- Reads from your uploaded table
GROUP BY 
    c.gender;                     -- Groups rows by gender category

    --Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
    c.customer_id,
    c.purchase_amount
FROM 
    dbo.customer_shopping_behavior AS c
WHERE 
    c.discount_applied = 'Yes'
    AND c.purchase_amount >= (
        SELECT AVG(purchase_amount) 
        FROM dbo.customer_shopping_behavior
    );

    --top 5 product have highest rating
    SELECT TOP 5 *
FROM dbo.customer_shopping_behavior AS c
ORDER BY c.review_rating DESC;


SELECT TOP 5 
  c.item_purchased,
  AVG(cast(c.review_rating as float)) AS [average_rating]
FROM dbo.customer_shopping_behavior AS c
GROUP BY c.item_purchased
ORDER BY AVG(cast(c.review_rating as float)) DESC;

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
  c.item_purchased,
  round(AVG(TRY_CAST(c.review_rating AS FLOAT)),2) AS [average_rating]
FROM dbo.customer_shopping_behavior AS c
GROUP BY c.item_purchased
ORDER BY round(AVG(TRY_CAST(c.review_rating AS FLOAT)),2) DESC;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select c.shipping_type,round(AVG(c.purchase_amount),2) as [avg amount] from dbo.customer_shopping_behavior as c
where c.shipping_type in ('Standard','Express')
group by c.shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select 
c.subscription_status,
COUNT(c.customer_id) as [Total_customer],
round(AVG(c.purchase_amount),2) as [avg_spend],
round(sum(c.purchase_amount),2) as [total_Revenue]
from dbo.customer_shopping_behavior as c
group by c.subscription_status
order by round(sum(c.purchase_amount),2),round(AVG(c.purchase_amount),2)

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 
    c.item_purchased,
    ROUND(
        (CAST(SUM(CASE WHEN c.discount_applied = 'Yes' THEN 1 ELSE 0 END) AS FLOAT) 
        / COUNT(*)) * 100, 
    2) AS [Discount Rate (%)]
FROM 
    dbo.customer_shopping_behavior AS c
GROUP BY 
    c.item_purchased
ORDER BY 
    [Discount Rate (%)] DESC;
    --Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
    WITH Customer_type AS (
    SELECT 
        c.customer_id,
        c.previous_purchases,
        CASE 
            WHEN c.previous_purchases = 1 THEN 'New'
            WHEN c.previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_Segment
    FROM 
        dbo.customer_shopping_behavior AS c
)
SELECT 
    Customer_Segment,
    COUNT(*) AS [Number of Customers]
FROM 
    Customer_type
GROUP BY 
    Customer_Segment;

    --Q8. What are the top 3 most purchased products within each category? 
WITH item_count AS (
    SELECT 
        c.category,
        c.item_purchased,
        COUNT(c.customer_id) AS [Total_orders],
        RANK() OVER(
            PARTITION BY c.category 
            ORDER BY COUNT(c.customer_id) DESC
        ) AS item_rank
    FROM 
        dbo.customer_shopping_behavior AS c
    GROUP BY 
        c.category, c.item_purchased
)
SELECT 
    category,
    item_purchased,
    item_rank,
    [Total_orders]
FROM 
    item_count
WHERE 
    item_rank <= 3
ORDER BY 
    category, item_rank;

    --Q8. What are the top 3 most purchased products within each category? 
WITH item_count AS (
    SELECT 
        c.category,
        c.item_purchased,
        COUNT(c.customer_id) AS [Total_orders],
        ROW_NUMBER() OVER(
            PARTITION BY c.category 
            ORDER BY COUNT(c.customer_id) DESC
        ) AS item_rank
    FROM 
        dbo.customer_shopping_behavior AS c
    GROUP BY 
        c.category, c.item_purchased
)
SELECT 
    category,
    item_purchased,
    item_rank,
    [Total_orders]
FROM 
    item_count
WHERE 
    item_rank <= 3
    --Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
    select  c.subscription_status,
    count(c.customer_id) as [reapt_buyers]
    from dbo.customer_shopping_behavior as c
    where c.previous_purchases>5
    group by c.subscription_status

--Q10. What is the revenue contribution of each age group? 
select c.age_group,
sum(c.purchase_amount) as [Total_revenue] 
from dbo.customer_shopping_behavior as c
group by c.age_group
order by [Total_revenue] desc