-- CREATE TABLE PERSON
create table person(
ID INT NOT NULL,
PERSON_NAME VARCHAR(50) NOT NULL,
BIRTH_DATE DATE,
PHONE VARCHAR(15) NOT NULL,
CONSTRAINT KUNAL PRIMARY KEY (ID)
)

SELECT * FROM person
-- EDIT THAT EXSITING TABLE
alter table person add EMAIL VARCHAR(50) NOT NULL

-- DROP TABLE FROM EXSITING TABLE
ALTER TABLE person DROP COLUMN PHONE

--DELETE TABLE
DROP TABLE person

